rm(list=ls())
install.packages(c("robvis","ggplot2","patchwork"))
library(robvis)
library(ggplot2)
library(patchwork)
setwd(getwd())
data <- readxl::read_xlsx("Data.xlsx")
a <- rob_summary(data, "ROB2",colour = c("#194d6f","#ff8f36","#7dceb2"))
b <- rob_traffic_light(data, "ROB2",colour = c("#194d6f","#ff8f36","#7dceb2"))
a+b+plot_layout(width=c(5,6))
export::graph2tif(file="figure 1",width=20,height=8)